import avatar1 from "../../assets/avatar_1.png"
import avatar2 from "../../assets/avatar_2.png"
import avatar3 from "../../assets/avatar_3.png"

// Dummy orders
export const pendingOrders = [
    {
        id: "ORD-1234",
        customer: "Alex Johnson",
        location: "Floor 3, Desk 42",
        items: ["Chicken Salad", "Sparkling Water"],
        placedAt: "12:00 PM",
        dueAt: "13:45 PM",
        notes: ["[Chicken Salad] Extra dressing on the side"],
        status: "readyForPickup",
        time: "Due 2 mins ago",
        avatar: avatar1,
        priority: "high",
        floor: "3",
        deskId: "42",
        coordinates: { x: 65, y: 5 },
      },
      {
        id: "ORD-1235",
        customer: "Sarah Miller",
        location: "Floor 2, Meeting Room B",
        items: ["Veggie Wrap", "Green Tea", "Chocolate Brownie"],
        placedAt: "11:43 AM",
        dueAt: "12:30 PM",
        notes: ["[Veggie Wrap] No lettuce"],
        status: "orderPlaced",
        time: "Due in 5 mins",
        avatar: avatar2,
        priority: "medium",
        floor: "2",
        deskId: "MR-B",
        coordinates: { x: 65, y: 65 },
      },
      {
        id: "ORD-1236",
        customer: "David Chen",
        location: "Floor 4, Desk 15",
        items: ["Beef Burger", "Fries", "Cola"],
        placedAt: "10:39 AM",
        dueAt: "13:00 PM",
        notes: [],
        status: "beingPrepared",
        time: "Due in 7 mins",
        avatar: avatar3,
        priority: "medium",
        floor: "4",
        deskId: "15",
        coordinates: { x: 45, y: 30 },
      },
      {
        id: "ORD-1237",
        customer: "Emily Davis",
        location: "Floor 1, Desk 5",
        items: ["Caesar Salad", "Iced Tea"],
        placedAt: "09:00 AM",
        dueAt: "10:30 AM",
        notes: ["[Caesar Salad] No croutons"],
        status: "orderPlaced",
        time: "Due in 10 mins",
        avatar: avatar1,
        priority: "low",
        floor: "1",
        deskId: "5",
        coordinates: { x: 20, y: 80 },
      },
  ];


  export const completedOrders = [
    {
      timePlaced: "09:00 AM",
      orderNumber: "ORD001",
      order: "Margherita Pizza",
      specialRequests: "Extra Cheese",
      extras: "Garlic Bread",
      status: "Completed",
    },
    {
      timePlaced: "11:15 AM",
      orderNumber: "ORD002",
      order: "Veggie Burger",
      specialRequests: "No Mayo",
      extras: "Sweet Potato Fries",
      status: "In Progress",
    },
    {
      timePlaced: "12:00 PM",
      orderNumber: "ORD003",
      order: "Chicken Caesar Salad",
      specialRequests: "Dressing on the Side",
      extras: "Breadsticks",
      status: "Pending",
    },
    {
      timePlaced: "12:00 PM",
      orderNumber: "ORD003",
      order: "Chicken Caesar Salad",
      specialRequests: "Dressing on the Side",
      extras: "Breadsticks",
      status: "Pending",
    },
  
  ];